/**
 * Emit a TypeScript config file from a built registry.
 *
 * The output is deliberately deterministic — sorted keys, consistent
 * formatting — so that re-running `init` on an unchanged schema produces a
 * byte-identical output. That matters for version control hygiene.
 */

import type { BinaryUuidConfig } from '../src/config/types.js';

const HEADER = `// AUTO-GENERATED by \`prisma-extension-binary-uuid init\`.
//
// Re-run the CLI after schema changes, OR edit this file by hand. Either way,
// \`prisma-extension-binary-uuid validate\` will flag drift against schema.prisma.
//
// This file is committed to version control. Your extension setup imports it:
//
//   import { uuidConfig } from './uuid-config';
//   const prisma = new PrismaClient().$extends(createBinaryUuidExtension(uuidConfig));
`;

export function emitConfig(config: BinaryUuidConfig): string {
  const sortedFields = sortMapKeys(config.fields);
  const autoGen = config.autoGenerate;
  const relations = config.relations;

  const lines: string[] = [];
  lines.push(HEADER);
  lines.push(`import { defineBinaryUuidConfig } from 'prisma-extension-binary-uuid';\n`);
  lines.push(`export const uuidConfig = defineBinaryUuidConfig({`);
  lines.push(`  fields: {`);
  for (const model of Object.keys(sortedFields)) {
    const fieldList = sortedFields[model]!.slice()
      .sort()
      .map((f) => `'${f}'`)
      .join(', ');
    lines.push(`    ${model}: [${fieldList}],`);
  }
  lines.push(`  },`);

  if (autoGen !== undefined && Object.keys(autoGen).length > 0) {
    const sortedAutoGen = sortMapKeys(autoGen);
    lines.push(`  autoGenerate: {`);
    for (const model of Object.keys(sortedAutoGen)) {
      const fieldList = sortedAutoGen[model]!.slice()
        .sort()
        .map((f) => `'${f}'`)
        .join(', ');
      lines.push(`    ${model}: [${fieldList}],`);
    }
    lines.push(`  },`);
  }

  if (relations !== undefined && Object.keys(relations).length > 0) {
    const sortedRelations: Record<string, Record<string, string>> = {};
    for (const model of Object.keys(relations).sort()) {
      sortedRelations[model] = {};
      for (const key of Object.keys(relations[model]!).sort()) {
        sortedRelations[model]![key] = relations[model]![key]!;
      }
    }
    lines.push(`  relations: {`);
    for (const model of Object.keys(sortedRelations)) {
      const parts = Object.entries(sortedRelations[model]!)
        .map(([k, v]) => `${k}: '${v}'`)
        .join(', ');
      lines.push(`    ${model}: { ${parts} },`);
    }
    lines.push(`  },`);
  }

  lines.push(`});`);
  lines.push('');

  return lines.join('\n');
}

function sortMapKeys<T>(map: Readonly<Record<string, T>>): Record<string, T> {
  const out: Record<string, T> = {};
  for (const key of Object.keys(map).sort()) {
    out[key] = map[key]!;
  }
  return out;
}
