/**
 * Emit DBA-grade SQL to migrate existing CHAR(36) UUID columns to BINARY(16).
 *
 * Strategy (per column, wrapped in a single transaction with FK checks off):
 *   1. ADD temp BINARY(16) column adjacent to the current CHAR(36) column
 *   2. UPDATE table SET temp_col = <dialect-specific string-to-binary fn>
 *   3. DROP original column
 *   4. RENAME temp_col TO original name
 *   5. Re-add PK / FK / indexes from metadata
 *
 * MySQL uses `UUID_TO_BIN(col, 1)` with the bit-swap flag for better B-tree
 * locality on timestamp-ordered UUIDs. MariaDB has no such function; we emit
 * the portable `UNHEX(REPLACE(col, '-', ''))` form and skip the bit-swap.
 * Callers wanting the bit-swap semantics on MariaDB should regenerate IDs
 * via the extension's UUIDv7 generator post-migration.
 *
 * This script is destructive and must run in a maintenance window. The SQL is
 * emitted, not executed — the DBA reviews and runs it manually.
 */

import type { ParsedSchema } from './parse-schema.js';

export type SqlDialect = 'mysql' | 'mariadb';

export interface MigrationSqlOptions {
  readonly schemaName?: string; // default: current database
  readonly includeDropFkPhase?: boolean; // default: true
  readonly swapFlag?: 0 | 1; // UUID_TO_BIN swap flag — default 1 (time-ordered v7 optimization). Ignored on MariaDB.
  readonly dialect?: SqlDialect; // default: 'mysql'
}

const HEADER = `-- AUTO-GENERATED by \`prisma-extension-binary-uuid migrate-sql\`.
--
-- Review this script with your DBA before running it. It is destructive.
-- Run in a maintenance window with application writes paused.
--
-- Convention: each section wraps a single logical step. Run sections in order.
-- Do not interleave. If a section fails midway, restore from backup before
-- re-running.
--
`;

export function emitMigrationSql(schema: ParsedSchema, options: MigrationSqlOptions = {}): string {
  const dialect: SqlDialect = options.dialect ?? 'mysql';
  const swapFlag = options.swapFlag ?? 1;
  const toBinExpr = (colRef: string): string =>
    dialect === 'mariadb'
      ? `UNHEX(REPLACE(${colRef}, '-', ''))`
      : `UUID_TO_BIN(${colRef}, ${swapFlag})`;
  const lines: string[] = [];
  lines.push(HEADER);
  lines.push(`-- Dialect: ${dialect}`);
  lines.push('');

  // Preflight: relax FK checks so we can drop/recreate columns referenced by FKs.
  lines.push('-- Phase 0: preflight');
  lines.push('SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;');
  lines.push('SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;');
  lines.push('SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = "TRADITIONAL,ALLOW_INVALID_DATES";');
  lines.push('');

  // Per-model, per-UUID-field column transform.
  lines.push('-- Phase 1: convert UUID columns from CHAR(36) to BINARY(16)');
  for (const model of schema.models) {
    const uuidFields = model.fields.filter(
      (f) => f.isUuidCandidate && (f.type === 'String' || f.type === 'Bytes'),
    );
    if (uuidFields.length === 0) continue;

    const tableName = model.name; // Prisma's default mapping: model name = table name unless @@map
    lines.push(`-- Model: ${model.name}`);
    for (const field of uuidFields) {
      if (field.dbType === 'Binary(16)') {
        // Already binary — skip.
        lines.push(`-- skipping ${tableName}.${field.name} (already BINARY(16))`);
        continue;
      }
      const nullable = field.isNullable ? ' NULL' : ' NOT NULL';
      lines.push(
        `ALTER TABLE \`${tableName}\` ADD COLUMN \`${field.name}__bin\` BINARY(16)${nullable} AFTER \`${field.name}\`;`,
      );
      lines.push(
        `UPDATE \`${tableName}\` SET \`${field.name}__bin\` = ${toBinExpr(
          `\`${field.name}\``,
        )} WHERE \`${field.name}\` IS NOT NULL;`,
      );
      lines.push(`ALTER TABLE \`${tableName}\` DROP COLUMN \`${field.name}\`;`);
      lines.push(
        `ALTER TABLE \`${tableName}\` CHANGE COLUMN \`${field.name}__bin\` \`${field.name}\` BINARY(16)${nullable};`,
      );
    }
    lines.push('');
  }

  lines.push('-- Phase 2: recreate indexes and foreign keys');
  lines.push('--');
  lines.push('-- After the column transformations above, run `prisma db push` against the');
  lines.push('-- new schema (where UUID fields are `Bytes @db.Binary(16)`). Prisma will');
  lines.push('-- detect that the columns already match and will only (re)create the');
  lines.push('-- indexes and foreign-key constraints that were dropped when columns were');
  lines.push('-- rebuilt. This avoids hand-rolled FK SQL here.');
  lines.push('');

  // Reset session flags.
  lines.push('-- Phase 3: restore session flags');
  lines.push('SET SQL_MODE = @OLD_SQL_MODE;');
  lines.push('SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;');
  lines.push('SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;');
  lines.push('');

  lines.push('-- Done. Verify row counts match pre-migration expectations before');
  lines.push('-- resuming writes.');

  return lines.join('\n');
}
