name: Compatibility report
description: 'A specific Prisma/MySQL/MariaDB version combo that should work'
labels: [compatibility]
body:
  - type: input
    id: prisma-version
    attributes:
      label: Prisma Client version
    validations:
      required: true

  - type: input
    id: db-version
    attributes:
      label: Database version
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: What works? What doesn't? Error messages?
    validations:
      required: true
